extends RefCounted
const SETUP := preload("res://tests/physics/test_placement.gd")
func run(h: SceneTree) -> void:
	var helper = SETUP.new()
	for trial in range(10):
		var room: RoomController = load("res://tests/scenes/physics_fixture.tscn").instantiate()
		room.spawn_player = true
		h.root.add_child(room)
		var plate: PressurePlate = load("res://scenes/puzzle/pressure_plate.tscn").instantiate()
		plate.position = Vector3(-3.5, 0, 3)
		plate.required_weight = 2
		room.add_child(plate)
		var door: ExitDoor = load("res://scenes/puzzle/exit_door.tscn").instantiate()
		door.position = Vector3(5, 0, 0)
		room.add_child(door)
		var first: Corpse = helper.add_body(room, Vector3(-4.4, 0.38, 3))
		var second: Corpse = helper.add_body(room, Vector3(-2.5, 0.38, 3))
		await h.frames(60)
		h.check(plate.weight() == 2 and door.is_open and door.get_node("Blocker/Shape").disabled, "FR020.two_direct_bodies.%d" % trial)
		var stacked: Corpse = helper.add_body(room, Vector3(-4.4, 0.82, 3))
		await h.frames(60)
		h.check(plate.weight() == 3 and door.is_open and not stacked.freeze, "FR020.stacked_bodies_each_count")
		room.state.remove_body(second.body_id)
		room._remove_prop(second.body_id)
		room._sync_contacts()
		h.check(plate.weight() == 2 and door.is_open and not door.get_node("Blocker/Shape").disabled, "EC07.immediate_contributor_removal")
		# Use a fresh collider for the direct-player test, avoiding contact teleports.
		room.remove_child(room.player)
		room.player.queue_free()
		room._spawn_subject()
		room.player.position = Vector3(-2.5, 0.13, 3)
		await h.frames(30)
		h.check(plate.weight() == 2 and door.is_open, "FR020.player_unit")
		room.state.pickup(room.state.epoch, room.state.subject_id, first.body_id)
		first.disable_prop()
		room._wake_bodies()
		room._sync_contacts()
		h.check(plate.weight() == 2 and door.is_open, "FR020.held_body_immediate_exclusion")
		await h.frames(60)
		h.check(absf(stacked.position.y - 0.345) < 0.04 and plate.weight() == 2, "EC06.pickup_support_settles_to_plate")
		# Door occupation is evaluated from current position, not a cached Area signal.
		room.remove_child(room.player)
		room.player.queue_free()
		room._spawn_subject()
		room.player.position = Vector3(5, 0.02, 0)
		door.set_open(true, room.player)
		door.set_open(false, room.player)
		h.check(room.player.global_position.distance_to(door.get_node("Retreat").global_position) < 0.01 and room.player.alive and not door.is_open, "EC15.safe_entry_retreat")
		h.check(room.is_reserved_pose(Transform3D(Basis.IDENTITY, door.get_node("Retreat").global_position)), "EC15.retreat_reserved_from_placement")
		await helper.dispose(h, room)
